name: ekoparty 

on:
  workflow_call:
    secrets:
      HAWK_API_KEY:
        required: true
  push:
    branches: [master]    

jobs:

  security_sast:
    uses: ./.github/workflows/security_sast.yml

  deploy-heroku:
    name: Deploy Heroku
    runs-on: ubuntu-latest
    needs: security_sast
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ekoparty-dast" #Must be unique in Heroku
          heroku_email: "roxsrossve@gmail.com"
          remote_branch: "master"
          usedocker: true

  security_dast:
    uses: ./.github/workflows/security_dast.yml
